const strings = {
  CALCULATOR_APP: 'Calculator App',
  ERROR: 'Error',
  ONE: '1',
  TWO: '2',
  THREE: '3',
  FOUR: '4',
  FIVE: '5',
  SIX: '6',
  SEVEN: '7',
  EIGHT: '8',
  NINE: '9',
  ROMAN_ONE: 'I',
  ROMAN_TWO: 'II',
  ROMAN_THREE: 'III',
  ROMAN_FOUR: 'IV',
  ROMAN_FIVE: 'V',
  ROMAN_SIX: 'VI',
  ROMAN_SEVEN: 'VII',
  ROMAN_EIGHT: 'VIII',
  ROMAN_NINE: 'IX',
  PLUS_SIGN: '+',
  SUBTRACT_SIGN: '-',
  MULTIPLY_SIGN: 'x',
  DIVIDE_SIGN: '÷',
  AC: 'AC',
  C: 'C',
  SWITCH: 'Switch',
};
export default strings;
